
server:
  port: 8200

spring:
  application:
    name: custumer-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    url: jdbc:mysql://localhost:3306/testedb?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: secret 
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      uri:
      - http://localhost:8888
  profiles:
    active:
    - dev

eureka:
  client:
    service-url:
      default-zone: http://localhost:8671/eureka