
insert into
 COMMERCE_ITEMS(ID,SHOPPIN_CART_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,AMOUNT) 
values  (1,1,1000,2,5.0,10.00);

insert into
 COMMERCE_ITEMS(ID,SHOPPIN_CART_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,AMOUNT) 
values  (2,1,2000,3,2.0,6);

insert into
 COMMERCE_ITEMS(ID,SHOPPIN_CART_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,AMOUNT) 
values  (3,1,1000,2,5.0,10.00);

-- shopping cart - 2

insert into
 COMMERCE_ITEMS(ID,SHOPPIN_CART_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,AMOUNT) 
values  (4,2,1000,3,2.0,6);

insert into
 COMMERCE_ITEMS(ID,SHOPPIN_CART_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,AMOUNT) 
values  (5,2,2000,4,2.0,8);


