insert into SHOPPING_CARTS(ID,CUSTOMER_ID,STATUS) values (1,20,'INCOMPLETE');
insert into SHOPPING_CARTS(ID,CUSTOMER_ID,STATUS) values (2,20,'SUBMITTED');
insert into SHOPPING_CARTS(ID,CUSTOMER_ID,STATUS) values (3,3,'INCOMPLETE');
insert into SHOPPING_CARTS(ID,CUSTOMER_ID,STATUS) values (4,4,'INCOMPLETE');
insert into SHOPPING_CARTS(ID,CUSTOMER_ID,STATUS) values (5,4,'INCOMPLETE');

