server:
  port: 8300




spring:
  application:
    name: shopping-cart-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/testedb?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: secret 
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

  cloud:
    config:
      uri:
      - http://localhost:8888
  profiles:
    active:
    - dev    
    

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

